openapi: 3.0.3
info:
  title: Pokémon API
  version: 1.0.0
  description: API documentation for Pokémon
paths:
  /api/pokemon/{id}/:
    get:
      operationId: pokemon_detail
      summary: Retrieve a Pokémon by ID
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - pokemon
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PokemonDetail'
          description: ''
  /api/pokemon/info/{id}/:
    get:
      operationId: pokemon_info
      summary: Get Pokémon details by ID
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - pokemon
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PokemonInfo'
          description: ''
  /api/pokemons/:
    get:
      operationId: pokemon_list
      summary: List all Pokémon
      tags:
      - pokemons
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PokemonList'
          description: ''
  /api/pokemons/search:
    get:
      operationId: pokemon_search
      summary: Search Pokémon by name
      tags:
      - pokemons
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  schemas:
    Ability:
      type: object
      properties:
        name:
          type: string
        isHidden:
          type: boolean
      required:
      - isHidden
      - name
    About:
      type: object
      properties:
        species:
          type: string
        height:
          type: integer
        weight:
          type: integer
        abilities:
          type: array
          items:
            $ref: '#/components/schemas/Ability'
        gender:
          $ref: '#/components/schemas/Gender'
        eggGroups:
          type: array
          items:
            type: string
        eggCycle:
          type: string
      required:
      - abilities
      - eggCycle
      - eggGroups
      - gender
      - height
      - species
      - weight
    BaseStats:
      type: object
      properties:
        hp:
          type: integer
        attack:
          type: integer
        defense:
          type: integer
        specialAttack:
          type: integer
        specialDefense:
          type: integer
        speed:
          type: integer
        total:
          type: integer
      required:
      - attack
      - defense
      - hp
      - specialAttack
      - specialDefense
      - speed
      - total
    Evolution:
      type: object
      properties:
        evolutions_chain:
          type: array
          items:
            $ref: '#/components/schemas/EvolutionChain'
      required:
      - evolutions_chain
    EvolutionChain:
      type: object
      properties:
        name:
          type: string
        evolutionMethod:
          type: string
        level:
          type: integer
          nullable: true
        imageUrl:
          type: string
          format: uri
        methodImageUrl:
          type: string
          format: uri
          nullable: true
      required:
      - evolutionMethod
      - imageUrl
      - level
      - methodImageUrl
      - name
    Gender:
      type: object
      properties:
        male:
          type: number
          format: double
          nullable: true
        female:
          type: number
          format: double
          nullable: true
      required:
      - female
      - male
    PokemonDetail:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
          maxLength: 100
        padded_id:
          type: string
          maxLength: 10
        types:
          type: array
          items:
            type: string
            maxLength: 50
        color:
          type: string
          maxLength: 50
        sprite_url:
          type: string
          format: uri
      required:
      - color
      - id
      - name
      - padded_id
      - sprite_url
      - types
    PokemonInfo:
      type: object
      properties:
        id:
          type: integer
        number:
          type: integer
        image:
          type: string
          format: uri
        name:
          type: string
        types:
          type: array
          items:
            type: string
        about:
          $ref: '#/components/schemas/About'
        evolutions:
          $ref: '#/components/schemas/Evolution'
        baseStats:
          $ref: '#/components/schemas/BaseStats'
      required:
      - about
      - baseStats
      - evolutions
      - id
      - image
      - name
      - number
      - types
    PokemonList:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
          maxLength: 100
        number:
          type: string
          maxLength: 50
        types:
          type: array
          items:
            type: string
            maxLength: 50
        boxBg:
          type: string
          maxLength: 100
        svg:
          type: string
          format: uri
        error:
          type: string
          maxLength: 200
      required:
      - boxBg
      - id
      - name
      - number
      - svg
      - types
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
