name: Deploy to Render

on:
  push:
    branches:
      - main
      - integrate-render-server-host-to-ci-cd
    paths:
      - server/**

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Debug Secret
      run: echo ${{ secrets.Deploy }}

    - name: Debug Secret.Deploy.RENDER_DEPLOY_HOOK
      run: echo ${{ secrets.Deploy.RENDER_DEPLOY_HOOK }}

    - name: Trigger Render Deploy
      run: |
        curl -X POST ${{ secrets.Deploy.RENDER_DEPLOY_HOOK }}