name: Deploy to Render

on:
  push:
    branches:
      - main
    paths:
      - server/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Deploy

    steps:
    - name: Trigger Render Deploy
      run: |
        curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}