name: Deploy to Render

on:
  push:
    branches:
      - main
      - integrate-render-server-host-to-ci-cd
    paths:
      - server/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Deploy

    steps:
    - name: Debug Secret
      run: echo ${{ secrets }}

    - name: Debug Secret.RENDER_DEPLOY_HOOK
      run: echo ${{ secrets.RENDER_DEPLOY_HOOK }}

    - name: Trigger Render Deploy
      run: |
        curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}