name: Unit Tests

on:
  push:
    branches:
      - main  # This will run only on the main branch
  pull_request:
    branches:
      - main  # This will run only on pull requests targeting the main branch

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Watchman
        run: sudo apt-get install -y watchman

      - name: Install Dependencies
        run: yarn

      - name: Run Tests
        run: yarn test